import type { Metadata } from "next";
import { Urbanist } from "next/font/google"
import "./globals.css";
import { Header } from "@/components/header/header";
import { Footer } from "@/components/footer/footer";
import { ThemeProvider } from "@/components/themeProvider";

const urbanist = Urbanist({ subsets: ["latin"] })


export const metadata: Metadata = {
  title: "Tienda Tulas Personalizadas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${urbanist.className}  antialiased`}
      >
        <ThemeProvider 
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
